import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signOut, useSession } from "next-auth/react";

import Layout from "~/components/Layout";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="radius flex flex-col items-center gap-2 border p-4">
          <h1 className="text-lg">
            {session
              ? `Welcome Home, ${session.user.email}`
              : "Welcome Home, Guest"}
          </h1>
          <p>
            {session ? "You are authenticated" : "You are not authenticated"}
          </p>
          {session && (
            <div className="flex flex-row gap-2">
              <Link href={"/dashboard"} className="rounded border px-4 py-1">
                Dashboard
              </Link>
              <button
                onClick={() => signOut()}
                className="rounded border px-4 py-1"
              >
                Logout
              </button>
            </div>
          )}

          {!session && (
            <div className="flex flex-row gap-2">
              <Link href={"/auth/login"} className="rounded border px-4 py-1">
                Login
              </Link>
              <Link href={"/auth/signup"} className="rounded border px-4 py-1">
                Register
              </Link>
            </div>
          )}
        </div>
      </Layout>
    </>
  );
};

export default Home;
