import { type NextPage } from "next";
import Head from "next/head";

import Footer from "~/components/Layout/Footer";
import NavBar from "~/components/Layout/NavBar";
import ListMading from "~/components/ListMading";
import Heading from "~/components/ListMading/Heading";

const BookmarksPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bookmarks - Mading Skanic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="my-16 flex min-h-screen flex-col gap-16 overflow-x-hidden px-20">
        <Heading title="Bookmark" />
        <ListMading onlyBookmarked={true} />
      </main>
      <Footer />
    </>
  );
};

export default BookmarksPage;
