import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

const User: NextPage = () => {
  const router = useRouter();
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>{session?.user.name} - Mading Skanic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>User ID: {router.query.id}</p>
      <p>Username: {session?.user.name}</p>
      <p>Email: {session?.user.email}</p>
      <p>Role: {session?.user.role}</p>
    </>
  );
};

export default User;
